apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-db
  template:
    metadata:
      labels:
        app: chess-db
    spec:
      containers:
      - name: chess-db-app
        image: michav1/chess-db:0.1.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: task-pv-storage
          mountPath: /app/backend/data
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: chess-db-service
spec:
  selector:
    app: chess-db
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-db-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /chess-db/
        backend:
          service:
            name: chess-db-service
            port:
              number: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---